### ISSUE TITLE
Add support for .scss format

### ISSUE THREAD

**Issue by karol-majewski** [khrystalz/khrystalz-ui#2]
First of all: thank you for your work! This is by far the best theme out there. It's a pleasure to work with `.js`, `.jsx`, `.sass` and `.md` files, but would it be possible to add support for:

- `.scss` (choosing `SASS` for `.scss` files in bottom right corner of Brackets makes it highlight the syntax quite correctly, but the linter goes crazy),
- `.php`,
- `.twig` files?

Especially the first one shouldn't be too much of a hassle, since SASS config works for them just fine.

Let me know if I can help — your theme deserves it.

**Comment by unzico** [comment]
Hi Karol,

really appreciate your feedback.
I added `.php`. I'm afraid there is no exclusive stylesheet support for `.twig` files.
Also updated `.scss`, `.md`, and `.html`/`.xml` files for better readability.

Feel free to open a pull request in the future. :)
